name: flutter_podcast_manager
description: Podcast manager.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  # Navigation
  go_router: ^15.2.0
  # .env
  flutter_dotenv: ^5.2.1

  # Features
  feature_episodes:
    path: packages/features/episodes
  # Domain
  core_domain:
    path: packages/core/domain
  # Data
  core_data:
    path: packages/core/data

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
